    (defun recorre (lista)
    (princ(car lista))
    (princ " ")
    (if (not (null lista))
        (recorre (cdr lista))
    )
    )

    (defun recorre2 (lista)
    (format t "~A-> ~%" (car lista)
    (if lista 
        (recorre2 (cdr lista))
    )
    )    
    )

    (defun recorre3 (lista)
    (princ(car lista))
    (princ " ")
    (if (not (null lista)) 
        (recorre (cdr lista))
    )
    (format t "~%")
    (princ "dame un numero a buscar ")
    (setq x(read))
    (if ( member x lista) (princ "Si esta el numero")
    (princ "no existe el numero"))
    )